const EMBED_HEIGHT = 600;

const TWITTER_EMBED_HEIGHT = 645;

const EMBED_WIDTH = 330;

const FACEBOOK_IFRAME_HEIGHT = 600;

const FACEBOOK_IFRAME_WIDTH = 330;

export {
  EMBED_HEIGHT,
  TWITTER_EMBED_HEIGHT,
  EMBED_WIDTH,
  FACEBOOK_IFRAME_HEIGHT,
  FACEBOOK_IFRAME_WIDTH,
};
